name: actividad_flutter_01_09_2025
description: "Actividad: Bloc + Cubit + consumo de JSONPlaceholder"
publish_to: 'none' # remove this if you want to publish

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # HTTP requests
  http: ^0.13.6

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
